version: 2
jobs:
  build:
    docker:
      - image: ubuntu:16.04
    steps:
      - checkout
      - run:  chmod -R +x *.sh
      - run:  apt-get update && apt-get install -y git
      - run:  git clone https://github.com/sstephenson/bats.git && cd bats && ./install.sh /usr/local
      - run:  test/runTests.sh